const users = [
  {
    id: 1,
    name: "Alice",
    role: "Frontend Developer",
    location: "New York",
    profilePhoto: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 2,
    name: "Bob",
    role: "Backend Developer",
    location: "San Francisco",
    profilePhoto: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    name: "Carol",
    role: "Full Stack Developer",
    location: "Remote",
    profilePhoto: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    name: "David",
    role: "UI/UX Designer",
    location: "Los Angeles",
    profilePhoto: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    name: "Eve",
    role: "DevOps Engineer",
    location: "Austin",
    profilePhoto: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 6,
    name: "Frank",
    role: "Data Scientist",
    location: "Seattle",
    profilePhoto: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Grace",
    role: "Mobile Developer",
    location: "Chicago",
    profilePhoto: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "Hannah",
    role: "Product Manager",
    location: "San Diego",
    profilePhoto: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Ivy",
    role: "QA Engineer",
    location: "Miami",
    profilePhoto: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Jack",
    role: "Software Engineer",
    location: "Dallas",
    profilePhoto: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 11,
    name: "Karen",
    role: "Business Analyst",
    location: "Boston",
    profilePhoto: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 12,
    name: "Leo",
    role: "Network Engineer",
    location: "Phoenix",
    profilePhoto: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 13,
    name: "Mia",
    role: "Systems Administrator",
    location: "Denver",
    profilePhoto: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 14,
    name: "Nina",
    role: "Cloud Engineer",
    location: "Atlanta",
    profilePhoto: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Oscar",
    role: "Security Analyst",
    location: "Chicago",
    profilePhoto: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];

export default users;
